### ISSUE TITLE
Run unit tests on all architectectures from CI

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1135]
Currently we are only running [e2e tests](https://github.com/opentofu/opentofu/blob/main/.github/workflows/build.yml) for all architectures. As prompted by #1069, we should also be running unit tests on all architectures on PRs.

**Comment by IgnorantSapient** [comment]
Hey @janosdebugs 

I've got a branch going for this and here is a sample GH actions run: https://github.com/IgnorantSapient/opentofu/actions/runs/7564347885


Here is a draft PR to see the changes https://github.com/IgnorantSapient/opentofu/pull/1

Is this what you wanted?

This is my new

**Comment by janosdebugs** [comment]
Hey @IgnorantSapient, I believe it is, but I wonder why it doesn't reproduce #1069. @Yantrio could you please take a look at this?

**Comment by IgnorantSapient** [comment]
Hey @janosdebugs, now that 1.6.1 is out, have the architecture specific build issues been resolved?

**Comment by janosdebugs** [comment]
Hey @IgnorantSapient thanks for following up. the 32-bit issues have been resolved, could you give it another run to see if it passes? Thank you so much for your help!

**Comment by IgnorantSapient** [comment]
Hey @janosdebugs 

https://github.com/IgnorantSapient/opentofu/actions/runs/7671244959/job/20909192837?pr=1 The windows builds are still failing for latest main.

I'm guessing Potential race condition based on the logs  🤔?

**Comment by janosdebugs** [comment]
Thanks @IgnorantSapient I'll look into fixing those, I have a Windows box. Worst case the Windows test run will have to be disabled.

**Comment by janosdebugs** [comment]
OK, I just took a look at the failing tests on Windows, there's a bunch of stuff in there that's related to path parsing. In total, over 200 tests are failing, so it's not just a quick fix. @IgnorantSapient to not hold this up any longer, let's remove the Windows platform (as much as it pains me) and then at the other things can get tested.

**Comment by IgnorantSapient** [comment]
Before we remove windows, should we add it to the issue backlog @janosdebugs ?

**Comment by janosdebugs** [comment]
Good point, issue added.
